<a href="https://colab.research.google.com/github/nafilafiryal/data_mining/blob/main/5_Praktikum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [5]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

df_chap5 = pd.read_csv('Chapter05DataSet.csv')

kolom_pilihan = ['Family', 'Hobbies', 'Political', 'Professional', 'Religious', 'Social_Club', 'Support_Group']
df_chap5 = df_chap5[kolom_pilihan]

df_chap5 = df_chap5.replace({'true': True, 'false': False}).astype(bool)

frequent_items = apriori(df_chap5, min_support=0.22, use_colnames=True)

rules_chap5 = association_rules(frequent_items, metric="confidence", min_threshold=0.5)

print("Hasil Association Rules Dataset Chapter05:")
display(rules_chap5[['antecedents', 'consequents', 'support', 'confidence']])

Hasil Association Rules Dataset Chapter05:

   antecedents  consequents   support  confidence
0  (Religious)     (Family)  0.224519    0.536351
1     (Family)  (Religious)  0.224519    0.575847
2  (Religious)    (Hobbies)  0.238875    0.570645
3    (Hobbies)  (Religious)  0.238875    0.796172

In [6]:
df_resto = pd.read_csv('Restaurant.csv', header=None, names=["Borough", "Cuisine", "Grade"])
df_resto['Cuisine'] = df_resto['Cuisine'].str.strip()
df_resto['Grade'] = df_resto['Grade'].str.strip()
df_resto = df_resto[['Cuisine', 'Grade']]

df_resto_bool = pd.get_dummies(df_resto).astype(bool)

frequent_items_resto = apriori(df_resto_bool, min_support=0.005, use_colnames=True)

rules_resto = association_rules(frequent_items_resto, metric="confidence", min_threshold=0.5)

hasil_grade_a = rules_resto[rules_resto['consequents'] == frozenset({'Grade_A'})]

print("Hasil Association Rules Dataset Restaurant (Fokus Grade A):")
display(hasil_grade_a[['antecedents', 'consequents', 'support', 'confidence']])

Hasil Association Rules Dataset Restaurant (Fokus Grade A):

                               antecedents consequents   support  confidence
0                       (Cuisine_American)   (Grade_A)  0.134401    0.561963
1                         (Cuisine_Bakery)   (Grade_A)  0.016402    0.501702
2                (Cuisine_Cafe/Coffee/Tea)   (Grade_A)  0.022016    0.685432
3                        (Cuisine_Chicken)   (Grade_A)  0.008279    0.546456
4                         (Cuisine_Donuts)   (Grade_A)  0.011918    0.788950
5                         (Cuisine_French)   (Grade_A)  0.006499    0.556455
6                     (Cuisine_Hamburgers)   (Grade_A)  0.013125    0.728761
7   (Cuisine_Ice Cream Gelato Yogurt Ices)   (Grade_A)  0.006059    0.805473
8                        (Cuisine_Italian)   (Grade_A)  0.024492    0.513772
9                          (Cuisine_Other)   (Grade_A)  0.005931    0.720270
10                         (Cuisine_Pizza)   (Grade_A)  0.029450    0.533569
11                    (Cuisine_Sandwiches)   (Grade_A)  0.011862    0.720027